name: build

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: cybernop/fill-fhir-cache@v1
        with:
          project-dir: "."
      - uses: cybernop/build-fhir-profiles@v1
        with:
          sushi-version: 3.0.0-beta.1
          node-version: 18
          project-dir: "."
