name: build

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - run: npm install -g fsh-sushi
        shell: bash
      - run: sushi
        shell: bash
